# SPDX-FileCopyrightText: 2026 Alin-Petru Roșu <rosualinpetru@gmail.com>
# SPDX-License-Identifier: Apache-2.0
version = 1

# No comment syntax
[[annotations]]
path = [
    "**/.gitkeep",
    "**/py.typed",
    ".gitmessage",
    ".gitmodules",
    ".python-version",
    ".zenodo.json",
    "external/adapted.cdx.json",
    "external/blake3/blake3.cdx.json",
]
SPDX-FileCopyrightText = "2026 The vFHE Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs/*.md", "README.md"]
SPDX-FileCopyrightText = "2026 The vFHE Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/CODE_OF_CONDUCT.md"
SPDX-FileCopyrightText = "2026 The vFHE Authors"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# GitHub surfaces these raw to contributors
[[annotations]]
path = [
    ".github/CODEOWNERS",
    ".github/ISSUE_TEMPLATE/*.yml",
    ".github/PULL_REQUEST_TEMPLATE.md",
]
SPDX-FileCopyrightText = "2026 Alin-Petru Roșu <rosualinpetru@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"

# Legal notice reproduced verbatim
[[annotations]]
path = "NOTICE"
SPDX-FileCopyrightText = "2026 The vFHE Authors"
SPDX-License-Identifier = "Apache-2.0"
