# SPDX-FileCopyrightText: 2026 Alin-Petru Roșu <rosualinpetru@gmail.com>
# SPDX-License-Identifier: Apache-2.0

module = {
    'sources': files(
        'c/src/gadget.c',
        'c/src/lwe.c',
        'c/src/mgsw.c',
        'c/src/mlwe.c',
    ),
    'includes': [include_directories('c/include')],
    'headers': files('c/include/mlwe.h', 'c/include/rns-rlwe.h'),
    'cdefs': files('python/cdef/mlwe.cdef'),
}
