# SPDX-License-Identifier: Apache-2.0
blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://vfhe.zulipchat.com
    about: Questions and discussion happen on the VFHE Zulip.
