# SPDX-FileCopyrightText: 2026 Antonio Guimarães <antonio.guimaraes@imdea.org>
# SPDX-License-Identifier: Apache-2.0

module = {
    'sources': files('c/src/rscode_rns.c'),
    'includes': [include_directories('c/include')],
    'headers': files('c/include/rscode.h'),
    'cdefs': files('python/cdef/polycom.cdef'),
}
