from __future__ import annotations

import math

from vfhe.arith.complex import ComplexPolynomial, ComplexRing
from vfhe.misc.libvfhe import ffi
from vfhe.mlwe.mlwe import MLWE, MLWE_Key, MLWE_Scheme, MLWE_Set, Polynomial, Ring, repr


class CKKS_Scheme(MLWE_Scheme):
    def __init__(
        self,
        ring: Ring,
        scaling_factor: float = 2**30,
        module_rank: int = 1,
        special_primes: int = 0,
    ):
        super().__init__(ring, special_primes=special_primes, module_rank=module_rank)
        self.scaling_factor = scaling_factor
        self.complex_ring = ComplexRing(ring.N // 2, True)

    def encode(self, values: list[complex | float]) -> Polynomial:
        """Encodes a list of complex/float values into a Polynomial in the ciphertext ring."""
        assert len(values) == self.ring.N // 2, (
            f"Expected {self.ring.N // 2} values, got {len(values)}"
        )
        # Create a ComplexPolynomial and populate it with values
        c_poly = ComplexPolynomial(self.complex_ring)
        c_poly.from_array(values)
        # Transform to coefficient domain using IFFT
        c_poly.IFFT()
        # Scale by the scaling factor
        c_poly *= self.scaling_factor
        # Round and convert to RNS
        poly = c_poly.round_to_RNS_cpp(self.ring)

        # Restrict the RNS mask of the encoded polynomial to match normal primes (excluding special primes)
        # self.ring (= rings[0]) already excludes special primes, so use its mask directly
        ffi.cast("RNS_Polynomial", poly.obj).rns_mask = self.ring.mask

        return poly

    def decode(
        self, poly: Polynomial, scaling_factor: "float|None" = None
    ) -> list[complex]:
        """Decodes a Polynomial back into a list of complex values."""
        if scaling_factor is None:
            scaling_factor = self.scaling_factor

        # Reconstruct the coefficients modulo the active RNS mask
        mask = poly.rns_mask
        poly.to_coeff()
        rns = poly.get_coeff_matrix(repr=repr.coeff)

        active_primes = []
        active_res = []
        for i, idx in enumerate(poly.ring.prime_indices):
            if mask & (1 << idx):
                active_primes.append(poly.ring.primes[i])
                active_res.append(rns[i])

        # Perform CRT reconstruction
        from vfhe.arith.number_theory import crt

        q_l = math.prod(active_primes)
        coeffs = []
        for j in range(poly.ring.N):
            residues = [active_res[i][j] for i in range(len(active_primes))]
            val = crt(residues, active_primes)
            # Signed representation
            if val >= q_l // 2:
                val -= q_l
            coeffs.append(float(val))

        # Create a ComplexPolynomial and populate it with the coefficients
        c_poly = ComplexPolynomial(self.complex_ring)
        n_half = poly.ring.N // 2
        for i in range(n_half):
            c_poly[i] = complex(coeffs[i], coeffs[i + n_half])
        # Transform back to slot domain using FFT
        c_poly.FFT()
        # Divide by the scaling factor to return values in C
        return [val / scaling_factor for val in c_poly]

    def encrypt(self, message: Polynomial, key: MLWE_Key) -> CKKS_Ciphertext:
        """Encrypts a plaintext Polynomial message under the given MLWE key."""
        out = CKKS_Ciphertext(self)
        self.sample(message, key, out=out)
        return out

    def decrypt(self, ciphertext: MLWE, key: MLWE_Key) -> Polynomial:
        """Decrypts a ciphertext into a Polynomial (by calculating its phase)."""
        return self.phase(ciphertext, key)

    def rotate(
        self, ciphertext: MLWE, k: int, ksk: "MLWE_Set | list[MLWE_Set]"
    ) -> MLWE:
        """Rotates the slots of the ciphertext by k steps."""
        N = self.ring.N
        # Galois generator for rotation by k slots is 5^k mod 2N
        # The rotation group generated by 5 has order N/2
        k_mod = k % (N // 2)
        gen = pow(5, k_mod, 2 * N)
        return self.automorphism(ciphertext, gen, ksk)

    def gen_rotation_key(self, key: MLWE_Key, k: int) -> "MLWE_Set | list[MLWE_Set]":
        """Generates the rotation key (automorphism key-switching key) for rotation by k slots."""
        N = self.ring.N
        k_mod = k % (N // 2)
        gen = pow(5, k_mod, 2 * N)
        return self.gen_ksk_automorphism(key, key, gen)

    def rescale(self, ciphertext: CKKS_Ciphertext) -> CKKS_Ciphertext:
        """Divides (round_division) the ciphertext by the last active prime, and recomputes delta."""
        l = ciphertext.ell
        assert l >= 2, "Cannot rescale a ciphertext with level less than 2"

        last_prime_val = self.ring.primes[l - 1]
        target_ring = self.ring.quotient_ring(ell=l - 1)

        ciphertext.round_division(target_ring)
        ciphertext.delta = ciphertext.delta / last_prime_val
        return ciphertext

    def rational_rescale(self, ct: CKKS_Ciphertext) -> CKKS_Ciphertext:
        """
        Rescale from level (lvl) to (lvl+1) as planned in the residue system.
        """
        level = ct.lvl
        assert level < len(self.rings) - 1, (
            "Cannot rescale a ciphertext at the last level"
        )

        start_ring = ct.ring
        end_ring = self.rings[level + 1]

        # Build union ring robustly by merging primes from starting and ending rings
        from vfhe.arith.ntt import NTT_processor_instance

        key_ntt = (self.ring.N, self.ring.split_degree)
        prime_map = NTT_processor_instance.prime_to_index[key_ntt]
        union_primes = list(set(start_ring.primes + end_ring.primes))
        union_primes.sort(key=lambda p: prime_map[p])
        union_prime_sizes = [math.ceil(math.log2(p)) for p in union_primes]
        union_ring = Ring(
            self.ring.N,
            primes=union_primes,
            prime_size=union_prime_sizes,
            split_degree=self.ring.split_degree,
        )

        # Allocate new ciphertext at the next level
        res = CKKS_Ciphertext(self, lvl=level + 1)

        # Scale & lift, then round & divide for each 'a' polynomial
        for i in range(self.r):
            a_poly = ct.get_a_poly(i)
            a_lifted = a_poly.scaled_lift(union_ring)
            a_divided = a_lifted.round_division(end_ring)
            self.ring.lib.polynomial_copy_RNS_polynomial(res.obj_a_i(i), a_divided.obj)

        # Scale & lift, then round & divide for 'b' polynomial
        b_poly = ct.get_b_poly()
        b_lifted = b_poly.scaled_lift(union_ring)
        b_divided = b_lifted.round_division(end_ring)
        self.ring.lib.polynomial_copy_RNS_polynomial(res.obj_b(), b_divided.obj)

        # Calculate scaling factor change
        primes_start = start_ring.primes
        primes_end = end_ring.primes
        p_val = math.prod([p for p in primes_end if p not in primes_start])
        q_val = math.prod([q for q in primes_start if q not in primes_end])

        res.delta = ct.delta * p_val / q_val
        res.repr = repr.coeff

        return res


class CKKS_Ciphertext(MLWE):
    scheme: "CKKS_Scheme"  # narrows MLWE.scheme for the CKKS-only members

    def __init__(
        self, scheme: CKKS_Scheme, ell: "int|None" = None, lvl: "int|None" = None
    ):
        if lvl is None:
            lvl = (scheme.ring.ell - ell) if ell is not None else 0
        super().__init__(scheme, lvl=lvl)
        self.delta = scheme.scaling_factor

    def rescale(self) -> CKKS_Ciphertext:
        return self.scheme.rescale(self)

    def __mul__(self, other) -> CKKS_Ciphertext:
        if isinstance(other, CKKS_Ciphertext):
            assert self.scheme == other.scheme, (
                "Cannot multiply ciphertexts from different schemes"
            )
            assert self.ell == other.ell, (
                "Cannot multiply ciphertexts at different levels"
            )

            base_prod = super().__mul__(other)
            prod = CKKS_Ciphertext(self.scheme, ell=base_prod.ell)
            prod.copy_from(base_prod)
            prod.delta = self.delta * other.delta

            return self.scheme.rescale(prod)
        elif isinstance(other, Polynomial):
            base_prod = super().__mul__(other)
            prod = CKKS_Ciphertext(self.scheme, ell=base_prod.ell)
            prod.copy_from(base_prod)
            prod.delta = self.delta * self.scheme.scaling_factor

            return self.scheme.rescale(prod)
        else:
            base_prod = super().__mul__(other)
            prod = CKKS_Ciphertext(self.scheme, ell=base_prod.ell)
            prod.copy_from(base_prod)
            prod.delta = self.delta
            return prod
