# SPDX-FileCopyrightText: 2026 Alin-Petru Roșu <rosualinpetru@gmail.com>
# SPDX-License-Identifier: Apache-2.0

module = {
    'sources': files(
        'c/src/aes_rng.c',
        'c/src/normal.c',
        'c/src/prng.c',
    ),
    'includes': [include_directories('c/include')],
    'headers': files('c/include/crypto.h'),
}
