# SPDX-FileCopyrightText: 2026 Alin-Petru Roșu <rosualinpetru@gmail.com>
# SPDX-License-Identifier: Apache-2.0

module = {
    'sources': files('c/src/sumcheck.c'),
    'includes': [include_directories('c/include')],
    'headers': files('c/include/sumcheck.h'),
    'cdefs': files('python/cdef/sumcheck.cdef'),
}
