# SPDX-FileCopyrightText: 2026 Alin-Petru Roșu <rosualinpetru@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# Generated by the build from tools/_engines.py: (name, required capability),
# best first.
ENGINES: list[tuple[str, str | None]]
