# SPDX-FileCopyrightText: 2026 Alin-Petru Roșu <rosualinpetru@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# Sends a Zulip message; called on failure by the runs nobody is watching.
name: Alert

on:
  workflow_call:
    secrets:
      zulip-api-key:
        required: true

permissions: {}

jobs:
  zulip-alert:
    name: Zulip Alert
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Send message
        uses: zulip/github-actions-zulip/send-message@f675f2b4eb2a95fae974215476dcb7ad8dfeff6b # v2.0.2
        with:
          api-key: ${{ secrets.zulip-api-key }}
          content: >-
            ${{ format('❌ [{0}]({1}/{2}/actions/runs/{3}) failed on `{4}`',
            github.workflow, github.server_url, github.repository, github.run_id, github.ref_name) }}
          email: "github-ci-bot@vfhe.zulipchat.com"
          organization-url: "https://vfhe.zulipchat.com"
          to: "vfhe-ci"
          topic: ${{ github.workflow }}
          type: "stream"
